version: '3'
services:
  frontend:
    build:
      context: ./conference-room-booking
      dockerfile: Dockerfile
    ports:
      - "3002:80"
    restart: unless-stopped
    environment:
      - REACT_APP_API_URL=http://localhost:5000/api
    depends_on:
      - backend

  backend:
    build:
      context: ./conference-room-booking/server
      dockerfile: Dockerfile
    ports:
      - "5001:5001"
    restart: unless-stopped
    environment:
      - PORT=5000
      - JWT_SECRET=your-super-secret-jwt-key-change-this-in-production 